# Generated by Django 2.1.2 on 2019-01-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category_spent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category_left', models.DecimalField(decimal_places=2, max_digits=8)),
                ('month_number', models.PositiveSmallIntegerField()),
                ('year_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pmt_type', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Category')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=70, unique=True)),
                ('group_couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Group')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.People'),
        ),
    ]
